db:
    name: mimic
    host: 127.0.0.1
    user: some_db_user
    pw: some_db_password
save_intermediate: True
event_type: admission
include_medications: False # only if POE type
case_notion: hostpital admission
case_attributes: [] # could be None, too
low_level_tables: # only if event type OTHER
    - procedureevents
    - labevents
cohort:
    icd_codes: # could also be []
        - M54.5
        - M54.0
    icd_version: 10
    icd_seq_num: 1
    drg_codes: [] # could also be a list
    drg_ontology: APR
    age:
        - 0:25
        - 50:90